// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrAIDdlaigpB8jq_sWmfCUZwr5r1_BXfc',
    appId: '1:871300475560:web:9e73ee84f0dadd6755709d',
    messagingSenderId: '871300475560',
    projectId: 'chatverse-56687',
    authDomain: 'chatverse-56687.firebaseapp.com',
    storageBucket: 'chatverse-56687.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWLOYQSrPCNqZ_IVx0LLiDuSHMueM83z0',
    appId: '1:871300475560:android:a145ce180af52c4655709d',
    messagingSenderId: '871300475560',
    projectId: 'chatverse-56687',
    storageBucket: 'chatverse-56687.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyKpEbWPLidOmjmDgXWb5VNcAfpLWgtKA',
    appId: '1:871300475560:ios:9a4a09e67e90d12955709d',
    messagingSenderId: '871300475560',
    projectId: 'chatverse-56687',
    storageBucket: 'chatverse-56687.appspot.com',
    iosClientId: '871300475560-taoq6dreclq5hvhqed29fd62lbad954m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyKpEbWPLidOmjmDgXWb5VNcAfpLWgtKA',
    appId: '1:871300475560:ios:df0d22c4a79aeef755709d',
    messagingSenderId: '871300475560',
    projectId: 'chatverse-56687',
    storageBucket: 'chatverse-56687.appspot.com',
    iosClientId: '871300475560-ho4fqogjrrm41ueiqf7bcvb1kraksjt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatverse.RunnerTests',
  );
}
